# The Okta software accompanied by this notice is provided pursuant to the following terms:
# Copyright © 2026-Present, Okta, Inc.
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the
# License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and limitations under the License.
# coding: utf-8

"""Core networking, OAuth2 primitives, token models, and storage interfaces."""

from .authentication import (
    AuthenticationContext,
    AuthenticationFlow,
    AuthenticationListener,
    AuthenticationState,
    BaseAuthenticationFlow,
    PKCEData,
    StandardAuthenticationContext,
    generate_pkce,
)
from .coalesced_result import CoalescedResult
from .codable import Codable
from .expires import Expires
from .key_provider import (
    DefaultKeyProvider,
    KeyProvider,
    LocalKeyProvider,
    get_key_provider,
    set_key_provider,
)
from .networking import (
    APIAuthorization,
    APIClient,
    APIClientConfiguration,
    APIClientListener,
    APIContentType,
    APIParsingContext,
    APIRateLimit,
    APIRequest,
    APIRequestBody,
    APIRequestBodyMixin,
    APIRequestMethod,
    APIResponse,
    APIRetry,
    BaseAPIRequest,
    DefaultNetworkInterface,
    HTTPRequest,
    ListenerCollection,
    NetworkInterface,
    RawResponse,
    RequestValue,
    RequestValueConvertible,
)
from .oauth2 import (
    JWK,
    JWKS,
    JWT,
    ClientAssertionAuthorization,
    ClientAuthorization,
    ClientIdAuthorization,
    ClientSecretAuthorization,
    ConfigurationError,
    ConfigurationFileNotFoundError,
    ConfigurationParseError,
    DefaultTokenHashValidator,
    DefaultTokenValidator,
    HasClaims,
    IdTokenClaim,
    IDTokenValidatorContext,
    InvalidConfigurationError,
    JWTBearerClaims,
    JWTType,
    JWTUsageContext,
    JWTValidationContext,
    OAuth2APIRequest,
    OAuth2APIRequestCategory,
    OAuth2ClientConfiguration,
    OAuth2Error,
    OAuth2TokenRequest,
    OAuth2TokenRequestDefaults,
    OpenIdConfiguration,
    ProvidesOAuth2Parameters,
    TokenHashValidator,
    TokenInfo,
    TokenValidator,
    UserInfo,
    get_access_token_validator,
    get_device_secret_validator,
    get_token_validator,
    set_access_token_validator,
    set_device_secret_validator,
    set_token_validator,
)
from .oauth2.client import OAuth2Client, OAuth2ClientListener
from .oauth2.refresh_token import RefreshTokenFlow, RefreshTokenRequest
from .time_coordinator import (
    DefaultTimeCoordinator,
    TimeCoordinator,
    get_time_coordinator,
    set_time_coordinator,
)
from .token import (
    GrantedTokenType,
    Token,
    TokenContext,
)

__all__ = [
    "JWK",
    "JWKS",
    "JWT",
    "APIAuthorization",
    "APIClient",
    "APIClientConfiguration",
    "APIClientListener",
    "APIContentType",
    "APIParsingContext",
    "APIRateLimit",
    "APIRequest",
    "APIRequestBody",
    "APIRequestBodyMixin",
    "APIRequestMethod",
    "APIResponse",
    "APIRetry",
    "AuthenticationContext",
    "AuthenticationFlow",
    "AuthenticationListener",
    "AuthenticationState",
    "BaseAPIRequest",
    "BaseAuthenticationFlow",
    "ClientAssertionAuthorization",
    "ClientAuthorization",
    "ClientIdAuthorization",
    "ClientSecretAuthorization",
    "CoalescedResult",
    "Codable",
    "ConfigurationError",
    "ConfigurationFileNotFoundError",
    "ConfigurationParseError",
    "DefaultKeyProvider",
    "DefaultNetworkInterface",
    "DefaultTimeCoordinator",
    "DefaultTokenHashValidator",
    "DefaultTokenValidator",
    "Expires",
    "GrantedTokenType",
    "HTTPRequest",
    "HasClaims",
    "IDTokenValidatorContext",
    "IdTokenClaim",
    "InvalidConfigurationError",
    "JWTBearerClaims",
    "JWTType",
    "JWTUsageContext",
    "JWTValidationContext",
    "KeyProvider",
    "ListenerCollection",
    "LocalKeyProvider",
    "NetworkInterface",
    "OAuth2APIRequest",
    "OAuth2APIRequestCategory",
    "OAuth2Client",
    "OAuth2ClientConfiguration",
    "OAuth2ClientListener",
    "OAuth2Error",
    "OAuth2TokenRequest",
    "OAuth2TokenRequestDefaults",
    "OpenIdConfiguration",
    "PKCEData",
    "ProvidesOAuth2Parameters",
    "RawResponse",
    "RefreshTokenFlow",
    "RefreshTokenRequest",
    "RequestValue",
    "RequestValueConvertible",
    "StandardAuthenticationContext",
    "TimeCoordinator",
    "Token",
    "TokenContext",
    "TokenHashValidator",
    "TokenInfo",
    "TokenValidator",
    "UserInfo",
    "generate_pkce",
    "get_access_token_validator",
    "get_device_secret_validator",
    "get_key_provider",
    "get_time_coordinator",
    "get_token_validator",
    "set_access_token_validator",
    "set_device_secret_validator",
    "set_key_provider",
    "set_time_coordinator",
    "set_token_validator",
]
